[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x686868"
blue = "0x5454ff"
cyan = "0x54ffff"
green = "0x54ff54"
magenta = "0xff54ff"
red = "0xe80f0c"
white = "0xffffff"
yellow = "0xfcd703"

[colors.cursor]
cursor = "0xD8DEE9"
text = "0x2E3440"

[colors.normal]
black = "0x000000"
blue = "0x1818b2"
cyan = "0x18b2b2"
green = "0x18b218"
magenta = "0xb218b2"
red = "0xb21818"
white = "0xb2b2b2"
yellow = "0xfcd703"

[colors.primary]
background = "0x000000"
foreground = "0xffffff"

[font]
size = 7.0
